vich_uploader:
    db_driver: orm

    mappings:
        floor_map_images:
            uri_prefix: /images/floor
            upload_destination: '%kernel.project_dir%/public/images/floor'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        map_object_images:
            uri_prefix: /images/map_object
            upload_destination: '%kernel.project_dir%/public/images/map_object'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
