doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    types:
      ulid: Symfony\Bridge\Doctrine\Types\UlidType

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '13'
  orm:
    controller_resolver:
      auto_mapping: false
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      User:
        type: xml
        is_bundle: false
        dir: '%kernel.project_dir%/src/User/Infrastructure/Mapping'
        prefix: 'App\User\Domain\Entity'
        alias: User
      Navi:
        type: xml
        is_bundle: false
        dir: '%kernel.project_dir%/src/Navi/Infrastructure/Mapping'
        prefix: 'App\Navi\Domain\Entity'
        alias: Navi
